raise Exception('Exception is raised')
